#!/bin/bash

modprobe bcm2835-v4l2
i=0
while true
do
	. /home/pi/frame.txt
	echo "framerate= $framerate"
	echo "Scale= $scale"
	echo "Turn = $i"
	now=$(date +"%T")
	echo "Current time = $now"
#Adding the video streaming channel endpoint from Azure
	INGESTURI="rtmp://VideoStreamingChannelEndpointOnAzure/system1"
	ffmpeg -re -i /dev/video0 -vf scale=$scale -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -t 30 -r $framerate -g $twoframerate -f flv $INGESTURI
	i=$((i+1))
done
